//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meals_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meals_Menu()
        {
            this.Selected_Menu_For_Help = new HashSet<Selected_Menu_For_Help>();
        }
    
        public int Meals_Menu_Kod { get; set; }
        public int Organization_Kod { get; set; }
        public int Food_Type { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Status_Food Status_Food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_Menu_For_Help> Selected_Menu_For_Help { get; set; }
    }
}
