//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Food_OrganizationsEntities : DbContext
    {
        public Food_OrganizationsEntities()
            : base("name=Food_OrganizationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Type_User> Type_User { get; set; }
        public virtual DbSet<Epicenter> Epicenter { get; set; }
        public virtual DbSet<Food_Type> Food_Type { get; set; }
        public virtual DbSet<Meals_Menu> Meals_Menu { get; set; }
        public virtual DbSet<Needy> Needy { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Selected_Menu_For_Help> Selected_Menu_For_Help { get; set; }
        public virtual DbSet<Status_Food> Status_Food { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
        public virtual DbSet<Volunteer_Organizations> Volunteer_Organizations { get; set; }
        public virtual DbSet<Organization_Days> Organization_Days { get; set; }
    }
}
