//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodOrganizationsEntities : DbContext
    {
        public FoodOrganizationsEntities()
            : base("name=FoodOrganizationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Epicenter> Epicenters { get; set; }
        public virtual DbSet<Food_Type> Food_Type { get; set; }
        public virtual DbSet<Meals_Menu> Meals_Menu { get; set; }
        public virtual DbSet<Needy> Needies { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Organization_Days> Organization_Days { get; set; }
        public virtual DbSet<Organizer> Organizers { get; set; }
        public virtual DbSet<Selected_Menu_For_Help> Selected_Menu_For_Help { get; set; }
        public virtual DbSet<Status_Food> Status_Food { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_User> Type_User { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<Volunteer_Organizations> Volunteer_Organizations { get; set; }
    }
}
