//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Epicenters = new HashSet<Epicenter>();
            this.Meals_Menu = new HashSet<Meals_Menu>();
            this.Selected_Menu_For_Help = new HashSet<Selected_Menu_For_Help>();
            this.Users = new HashSet<User>();
            this.Volunteer_Organizations = new HashSet<Volunteer_Organizations>();
        }
    
        public int Organization_Kod { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_City { get; set; }
        public string Organization_Logo { get; set; }
        public string Organization_Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Epicenter> Epicenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meals_Menu> Meals_Menu { get; set; }
        public virtual Organization_Days Organization_Days { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected_Menu_For_Help> Selected_Menu_For_Help { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer_Organizations> Volunteer_Organizations { get; set; }
    }
}
