//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selected_Menu_For_Help
    {
        public int Selected_Menu_For_Help_Kod { get; set; }
        public int Meals_Menu_Kod { get; set; }
        public Nullable<int> Volunteer_Kod { get; set; }
        public System.DateTime Application_Date { get; set; }
        public int Needy_Kod { get; set; }
        public int Organizer_Kod { get; set; }
        public int Organization_Kod { get; set; }
    
        public virtual Meals_Menu Meals_Menu { get; set; }
        public virtual Needy Needy { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Organizer Organizer { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
